# SITE CONFIGURATION
baseurl: ''
url: https://heehotranslations.github.io/
theme: jekyll-theme-slate
title: Hee Ho Translations
description: Traducción de videojuegos al español
sidebars:
- navigation.yml